### ISSUE TITLE
Heart image benchmarks failing on main

### ISSUE THREAD

**Issue by K-Meech** [HEFTIEProject/zarr-benchmarks#98]
Running the benchmarks with the heart image and zarr-python v3 e.g.
```
tox run -e py313-zarrv3 -- --benchmark-only --image=heart --benchmark-storage=data/results/heart --rounds=1 --warmup-rounds=0
```

Throws an error (section of this copied at bottom of issue). It seems `zarr-python v3` can handle `"dtype":"<u2"` (as set in the sparse / dense zarr files), but not `"dtype":">u2"` as set in the heart file. This seems to be confirmed from issues stating that zarr v3 [doesn't support big-endian yet](https://github.com/zarr-developers/zarr-python/issues/3005). 

@dstansby - would it be possible to re-write the heart image as `<u2`?
```
cls = <enum 'DataType'>, dtype = dtype('>u2')

    @classmethod
    def from_numpy(cls, dtype: np.dtype[Any]) -> DataType:
        if dtype.kind in "UT":
            return DataType.string
        elif dtype.kind == "S":
            return DataType.bytes
        elif not _NUMPY_SUPPORTS_VLEN_STRING and dtype.kind == "O":
            # numpy < 2.0 does not support vlen string dtype
            # so we fall back on object array of strings
            return DataType.string
        dtype_to_data_type = {
            "|b1": "bool",
            "bool": "bool",
            "|i1": "int8",
            "<i2": "int16",
            "<i4": "int32",
            "<i8": "int64",
            "|u1": "uint8",
            "<u2": "uint16",
            "<u4": "uint32",
            "<u8": "uint64",
            "<f2": "float16",
            "<f4": "float32",
            "<f8": "float64",
            "<c8": "complex64",
            "<c16": "complex128",
        }
>       return DataType[dtype_to_data_type[dtype.str]]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E       KeyError: '>u2'

.tox\py313-zarrv3\Lib\site-packages\zarr\core\metadata\v3.py:704: KeyError
```

**Comment by dstansby** [comment]
I don't think I'll have time to do this before I go away so either we:

- Leave it failing and I'll fix when I'm back
- Turn off the zarr3 benchmarks for now until it's fixed in zarr-python 3 (I think it will be in version 3.1.0, which should be soon 🤞 )

**Comment by K-Meech** [comment]
The heart image has now been converted to `<u2` and uploaded to Zenodo. I've re-run the command above and it completes with no errors :tada:

I did notice that some of the old chunk folders were still present in the `zarr-benchmarks` `pooch` cache for the heart image. You may want to delete the existing cache [at the default location](https://www.fatiando.org/pooch/latest/api/generated/pooch.os_cache.html) to be sure no old files are remaining.
